services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 6500:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  service:
    container_name: segments
    build: .
    env_file:
      - .env
    ports:
      - "8080:3000"
    command: go run ./cmd/app/main.go

volumes:
  postgres: